## 1.Import SA2 shapefile

In [19]:
import shapefile
sf = shapefile.Reader("SA2/SA2_2016_AUST.shp", encoding="iso-8859-1")

In [3]:
import psycopg2
import psycopg2.extras

def pgconnect():
    # pleasereplace <your_unikey> and <your_SID> with your own details
    YOUR_UNIKEY = 'ysun8114'#'<your_unikey>'
    YOUR_PW     = '480341433'#'<your_SID>'
    try: 
        conn = psycopg2.connect(host='soit-db-pro-1.ucc.usyd.edu.au',
                                database='y19s1d2x01_'+YOUR_UNIKEY,
                                user='y19s1d2x01_'+YOUR_UNIKEY,
                                password=YOUR_PW) 
        print('connected')
    except Exception as e:
        print("unable to connect to the database")
        print(e)
    return conn

conn = pgconnect()

connected

In [4]:
def pgquery( conn, sqlcmd, args=None, msg=False, returntype='tuple'):
    retval = None
    with conn:
        cursortype = None if returntype != 'dict' else psycopg2.extras.RealDictCursor
        with conn.cursor(cursor_factory=cursortype) as cur:
            try:
                if args is None:
                    cur.execute(sqlcmd)
                else:
                    cur.execute(sqlcmd, args)
                if (cur.description != None ):
                    retval = cur.fetchall() # we use fetchall() as we expect only _small_ query results
                if msg != False:
                    print("success: " + msg)
            except psycopg2.DatabaseError as e:
                if e.pgcode != None and msg:
                    print("db read error: "+msg)
                    print(e)
            except Exception as e:
                print(e)
    return retval

In [20]:
aust_schema = '''CREATE TABLE AUST (
                     SA2_MAIN16 INTEGER, 
                     SA2_5DIG16 INTEGER, 
                     SA2_NAME16 VARCHAR(80), 
                     SA3_CODE16 INTEGER,
                     SA3_NAME16 VARCHAR(80),
                     SA4_CODE16 INTEGER,
                     SA4_NAME16 VARCHAR(80),
                     GCC_CODE16 VARCHAR(80),
                     GCC_NAME16 VARCHAR(80),
                     STE_CODE16 INTEGER,
                     STE_NAME16 VARCHAR(80),
                     AREASQKM16 INTEGER,
                     geom GEOMETRY(Polygon,4326),
                     CONSTRAINT aust_area_id_fkey FOREIGN KEY (SA2_MAIN16)
                     REFERENCES public.statisticalareas (area_id) MATCH SIMPLE)''' 

pgquery(conn, "DROP TABLE AUST",msg="cleared old table")
pgquery(conn, aust_schema, msg="created AUST table")

success: cleared old table
success: created AUST table

In [21]:
import re

insert_stmt = """INSERT INTO AUST VALUES ( %(SA2_MAIN16)s, %(SA2_5DIG16)s, %(SA2_NAME16)s, %(SA3_CODE16)s, %(SA3_NAME16)s,
                                            %(SA4_CODE16)s, %(SA4_NAME16)s,%(GCC_CODE16)s,%(GCC_NAME16)s,%(STE_CODE16)s,
                                            %(STE_NAME16)s,%(AREASQKM16)s,
                                            ST_GEOMFROMTEXT(%(geom)s, 4326) )"""

shapes = sf.shapes()
records= sf.records()

row = {}
for i in range(0, len(shapes)):
    record = sf.record(i)
    shape  = sf.shape(i)
    row['SA2_MAIN16']=record[0]
    row['SA2_5DIG16']=record[1]
    row['SA2_NAME16']=record[2]
    row['SA3_CODE16']=record[3]
    row['SA3_NAME16']=record[4]
    row['SA4_CODE16']=record[5]
    row['SA4_NAME16']=record[6]
    row['GCC_CODE16']=record[7]
    row['GCC_NAME16']=record[8]
    row['STE_CODE16']=record[9]
    row['STE_NAME16']=record[10]
    row['AREASQKM16']=record[11]    
    row['geom']="POLYGON(("
    i=0
    for x, y in shape.points:
       row['geom']+="%s %s," % (x,y)
       # check for start of a new polygon part
       i += 1
       if i in shape.parts:
           row['geom']= re.sub(",$", "),(", row['geom'])
    # properly end the polygon string
    row['geom'] = re.sub(",$", "))", row['geom'])
    # finally: insert new row into the table
    if row['GCC_NAME16']=='Greater Sydney':pgquery(conn, insert_stmt, args=row, msg="inserted "+str(record[2]))

success: inserted Avoca Beach - Copacabana
success: inserted Box Head - MacMasters Beach
success: inserted Calga - Kulnura
success: inserted Erina - Green Point
success: inserted Gosford - Springfield
success: inserted Kariong
success: inserted Kincumber - Picketts Valley
success: inserted Narara
success: inserted Niagara Park - Lisarow
success: inserted Point Clare - Koolewong
success: inserted Saratoga - Davistown
success: inserted Terrigal - North Avoca
success: inserted Umina - Booker Bay - Patonga
success: inserted Wamberal - Forresters Beach
success: inserted Woy Woy - Blackwall
success: inserted Wyoming
success: inserted Bateau Bay - Killarney Vale
success: inserted Blue Haven - San Remo
success: inserted Budgewoi - Buff Point - Halekulani
success: inserted Chittaway Bay - Tumbi Umbi
success: inserted Gorokan - Kanwal - Charmhaven
success: inserted Jilliby - Yarramalong
success: inserted Lake Munmorah - Mannering Park
success: inserted Ourimbah - Fountaindale
success: inserted Summerland Point - Gwandalan
success: inserted The Entrance
success: inserted Toukley - Norah Head
success: inserted Tuggerah - Kangy Angy
success: inserted Warnervale - Wadalba
success: inserted Wyong
success: inserted Baulkham Hills (East)
success: inserted Baulkham Hills (West) - Bella Vista
success: inserted Glenhaven
success: inserted West Pennant Hills
success: inserted Castle Hill - Central
success: inserted Castle Hill - East
success: inserted Castle Hill - North
success: inserted Castle Hill - South
success: inserted Castle Hill - West
success: inserted Cherrybrook
success: inserted Kellyville
success: inserted Dural - Kenthurst - Wisemans Ferry
success: inserted Galston - Laughtondale
success: inserted Bilpin - Colo - St Albans
success: inserted Kurrajong Heights - Ebenezer
success: inserted Pitt Town - McGraths Hill
success: inserted Rouse Hill - Beaumont Hills
success: inserted Blacktown (East) - Kings Park
success: inserted Blacktown (North) - Marayong
success: inserted Doonside - Woodcroft
success: inserted Lalor Park - Kings Langley
success: inserted Seven Hills - Toongabbie
success: inserted Blacktown (South)
success: inserted Blacktown (West)
success: inserted Glenwood
success: inserted Parklea - Kellyville Ridge
success: inserted Riverstone - Marsden Park
success: inserted Acacia Gardens
success: inserted Quakers Hill
success: inserted Bidwill - Hebersham - Emerton
success: inserted Glendenning - Dean Park
success: inserted Hassall Grove - Plumpton
success: inserted Lethbridge Park - Tregear
success: inserted Mount Druitt - Whalan
success: inserted Prospect Reservoir
success: inserted Rooty Hill - Minchinbury
success: inserted Banksmeadow
success: inserted Botany
success: inserted Mascot - Eastlakes
success: inserted Pagewood - Hillsdale - Daceyville
success: inserted Port Botany Industrial
success: inserted Sydney Airport
success: inserted Marrickville
success: inserted Petersham - Stanmore
success: inserted Sydenham - Tempe - St Peters
success: inserted Darlinghurst
success: inserted Erskineville - Alexandria
success: inserted Glebe - Forest Lodge
success: inserted Newtown - Camperdown - Darlington
success: inserted Potts Point - Woolloomooloo
success: inserted Pyrmont - Ultimo
success: inserted Redfern - Chippendale
success: inserted Surry Hills
success: inserted Sydney - Haymarket - The Rocks
success: inserted Waterloo - Beaconsfield
success: inserted Bondi - Tamarama - Bronte
success: inserted Bondi Beach - North Bondi
success: inserted Bondi Junction - Waverly
success: inserted Centennial Park
success: inserted Double Bay - Bellevue Hill
success: inserted Dover Heights
success: inserted Paddington - Moore Park
success: inserted Rose Bay - Vaucluse - Watsons Bay
success: inserted Woollahra
success: inserted Coogee - Clovelly
success: inserted Malabar - La Perouse - Chifley
success: inserted Kensington (NSW)
success: inserted Kingsford
success: inserted Maroubra - North
success: inserted Maroubra - South
success: inserted Maroubra - West
success: inserted Randwick - North
success: inserted Randwick - South
success: inserted Bass Hill - Georges Hall
success: inserted Chullora
success: inserted Condell Park
success: inserted Greenacre - Mount Lewis
success: inserted Padstow
success: inserted Panania - Milperra - Picnic Point
success: inserted Revesby
success: inserted Yagoona - Birrong
success: inserted Bankstown - North
success: inserted Bankstown - South
success: inserted Belmore - Belfield
success: inserted Canterbury (South) - Campsie
success: inserted Kingsgrove (North) - Earlwood
success: inserted Punchbowl
success: inserted Roselands
success: inserted Lakemba
success: inserted Wiley Park
success: inserted Hurstville
success: inserted Mortdale - Penshurst
success: inserted Narwee - Beverly Hills
success: inserted Oatley - Hurstville Grove
success: inserted Peakhurst - Lugarno
success: inserted Riverwood
success: inserted South Hurstville - Blakehurst
success: inserted Arncliffe - Bardwell Valley
success: inserted Bexley
success: inserted Kingsgrove (South) - Bardwell Park
success: inserted Kogarah
success: inserted Kogarah Bay - Carlton - Allawah
success: inserted Monterey - Brighton-le-Sands - Kyeemagh
success: inserted Rockdale - Banksia
success: inserted Sans Souci - Ramsgate
success: inserted Concord - Mortlake - Cabarita
success: inserted Concord West - North Strathfield
success: inserted Drummoyne - Rodd Point
success: inserted Five Dock - Abbotsford
success: inserted Balmain
success: inserted Leichhardt - Annandale
success: inserted Lilyfield - Rozelle
success: inserted Ashfield
success: inserted Burwood - Croydon
success: inserted Canterbury (North) - Ashbury
success: inserted Croydon Park - Enfield
success: inserted Dulwich Hill - Lewisham
success: inserted Haberfield - Summer Hill
success: inserted Homebush
success: inserted Strathfield
success: inserted Strathfield South
success: inserted Chatswood (East) - Artarmon
success: inserted Chatswood (West) - Lane Cove North
success: inserted Lane Cove - Greenwich
success: inserted St Leonards - Naremburn
success: inserted Willoughby - Castle Cove - Northbridge
success: inserted Asquith - Mount Colah
success: inserted Berowra - Brooklyn - Cowan
success: inserted Normanhurst - Thornleigh - Westleigh
success: inserted Hornsby - East
success: inserted Hornsby - West
success: inserted Waitara - Wahroonga (West)
success: inserted Gordon - Killara
success: inserted Lindfield - Roseville
success: inserted Pymble
success: inserted St Ives
success: inserted Turramurra
success: inserted Wahroonga (East) - Warrawee
success: inserted Cremorne - Cammeray
success: inserted Crows Nest - Waverton
success: inserted Mosman
success: inserted Neutral Bay - Kirribilli
success: inserted North Sydney - Lavender Bay
success: inserted Balgowlah - Clontarf - Seaforth
success: inserted Manly - Fairlight
success: inserted Avalon - Palm Beach
success: inserted Bayview - Elanora Heights
success: inserted Newport - Bilgola
success: inserted Warriewood - Mona Vale
success: inserted Beacon Hill - Narraweena
success: inserted Cromer
success: inserted Dee Why - North Curl Curl
success: inserted Forestville - Killarney Heights
success: inserted Frenchs Forest - Belrose
success: inserted Freshwater - Brookvale
success: inserted Manly Vale - Allambie Heights
success: inserted Narrabeen - Collaroy
success: inserted Terrey Hills - Duffys Forest
success: inserted Camden - Ellis Lane
success: inserted Elderslie - Harrington Park
success: inserted Mount Annan - Currans Hill
success: inserted Bradbury - Wedderburn
success: inserted Campbelltown - Woodbine
success: inserted Claymore - Eagle Vale - Raby
success: inserted Holsworthy Military Area
success: inserted Ingleburn - Denham Court
success: inserted Leumeah - Minto Heights
success: inserted Macquarie Fields - Glenfield
success: inserted Minto - St Andrews
success: inserted Rosemeadow - Glen Alpine
success: inserted Bargo
success: inserted Douglas Park - Appin
success: inserted Picton - Tahmoor - Buxton
success: inserted The Oaks - Oakdale
success: inserted Blackheath - Megalong Valley
success: inserted Blaxland - Warrimoo - Lapstone
success: inserted Blue Mountains - North

success: inserted Katoomba - Leura
success: inserted Lawson - Hazelbrook - Linden
success: inserted Springwood - Winmalee
success: inserted Wentworth Falls
success: inserted Blue Mountains - South
success: inserted Cambridge Park
success: inserted Castlereagh - Cranebrook
success: inserted Emu Plains - Leonay
success: inserted Glenmore Park - Regentville
success: inserted Jamisontown - South Penrith
success: inserted Kingswood - Werrington
success: inserted Mulgoa - Luddenham - Orchard Hills
success: inserted Penrith
success: inserted Warragamba - Silverdale
success: inserted Richmond - Clarendon
success: inserted Windsor - Bligh Park
success: inserted Yarramundi - Londonderry
success: inserted Erskine Park
success: inserted St Clair
success: inserted Colyton - Oxley Park
success: inserted St Marys - North St Marys
success: inserted Homebush Bay - Silverwater
success: inserted Rookwood Cemetery
success: inserted Auburn - Central
success: inserted Auburn - North
success: inserted Auburn - South
success: inserted Berala
success: inserted Lidcombe
success: inserted Regents Park
success: inserted Carlingford
success: inserted Ermington - Rydalmere
success: inserted Oatlands - Dundas Valley
success: inserted Chester Hill - Sefton
success: inserted Fairfield - East
success: inserted Granville - Clyde
success: inserted Greystanes - Pemulwuy
success: inserted Guildford - South Granville
success: inserted Guildford West - Merrylands West
success: inserted Merrylands - Holroyd
success: inserted Smithfield Industrial
success: inserted Yennora Industrial
success: inserted North Parramatta
success: inserted North Rocks
success: inserted Northmead
success: inserted Parramatta - Rosehill
success: inserted Toongabbie - Constitution Hill
success: inserted Winston Hills
success: inserted Pendle Hill - Girraween
success: inserted Wentworthville - Westmead
success: inserted Epping - North Epping
success: inserted Pennant Hills - Cheltenham
success: inserted Eastwood - Denistone
success: inserted Gladesville - Huntleys Point
success: inserted Hunters Hill - Woolwich
success: inserted Macquarie Park - Marsfield
success: inserted North Ryde - East Ryde
success: inserted West Ryde - Meadowbank
success: inserted Putney
success: inserted Ryde
success: inserted Ashcroft - Busby - Miller
success: inserted Austral - Greendale
success: inserted Cobbitty - Leppington
success: inserted Badgerys Creek
success: inserted Cecil Hills
success: inserted Green Valley
success: inserted Hinchinbrook
success: inserted Hoxton Park - Carnes Hill - Horningsea Park
success: inserted West Hoxton - Middleton Grange
success: inserted Bonnyrigg Heights - Bonnyrigg
success: inserted Bossley Park - Abbotsbury
success: inserted Cabramatta - Lansvale
success: inserted Cabramatta West - Mount Pritchard
success: inserted Canley Vale - Canley Heights
success: inserted Edensor Park
success: inserted Fairfield
success: inserted Fairfield - West
success: inserted Greenfield Park - Prairiewood
success: inserted Horsley Park - Kemps Creek
success: inserted Smithfield - Wetherill Park
success: inserted St Johns Park - Wakeley
success: inserted Wetherill Park Industrial
success: inserted Casula
success: inserted Chipping Norton - Moorebank
success: inserted Holsworthy - Wattle Grove
success: inserted Liverpool
success: inserted Lurnea - Cartwright
success: inserted Prestons - Edmondson Park
success: inserted Warwick Farm
success: inserted Gymea - Grays Point
success: inserted Miranda - Yowie Bay
success: inserted Sylvania - Taren Point
success: inserted Caringbah
success: inserted Caringbah South
success: inserted Cronulla - Kurnell - Bundeena
success: inserted Lilli Pilli - Port Hacking - Dolans Bay
success: inserted Woolaware - Burraneer
success: inserted Heathcote - Waterfall
success: inserted Illawong - Alfords Point
success: inserted Menai - Lucas Heights - Woronora
success: inserted Oyster Bay - Como - Jannali
success: inserted Royal National Park
success: inserted Sutherland - Kirrawee
success: inserted Engadine
success: inserted Loftus - Yarrawarrah
success: inserted Woronora Heights

## 2.Import 5 csv file

In [22]:
#load five files
import csv
import pandas as pd
data_bikesharingpods=list(csv.DictReader(open('data/BikeSharingPods.csv')))
data_businessstats=list(csv.DictReader(open('data/BusinessStats.csv')))
data_censusstats=list(csv.DictReader(open('data/CensusStats.csv')))
data_neighbourhoods=list(csv.DictReader(open('data/Neighbourhoods.csv')))
data_statisticalareas=list(csv.DictReader(open('data/StatisticalAreas.csv')))

In [24]:
import pandas as pd

data_businessstats1=pd.read_csv('data/BusinessStats.csv')
business_mean={}
for i in data_businessstats1:
    business_mean[i]=int(data_businessstats1[i].mean()+0.5)
    
data_censusstats1=pd.read_csv('data/CensusStats.csv')
censuss_mean={}
for i in data_censusstats1:
    censuss_mean[i]=int(data_censusstats1[i].mean()+0.5)

data_neighbourhoods1=pd.read_csv('data//Neighbourhoods.csv')
neighbourhoods_mean={}
for i in data_neighbourhoods1:
    if i!='area_name':neighbourhoods_mean[i]=int(data_neighbourhoods1[i].mean()+0.5)

In [24]:
statisticalareas_schema=''' CREATE TABLE IF NOT EXISTS statisticalareas(
                        area_id integer NOT NULL,
                        area_name varchar(80),
                        parent_area_id integer,
                        CONSTRAINT statisticalareas_pkey PRIMARY KEY (area_id))'''


pgquery(conn, "DROP TABLE statisticalareas",msg="cleared old table")
pgquery(conn, statisticalareas_schema, msg="created statisticalareastable")

db read error: cleared old table
cannot drop table statisticalareas because other objects depend on it
DETAIL:  constraint bussinessstats_area_id_fkey on table businessstats depends on table statisticalareas
constraint censusstats_area_id_fkey on table censusstats depends on table statisticalareas
constraint neighbourhoods_area_id_fkey on table neighbourhoods depends on table statisticalareas
HINT:  Use DROP ... CASCADE to drop the dependent objects too.

success: created statisticalareastable

In [25]:
insert_stmt = """INSERT INTO statisticalareas(area_id,area_name,parent_area_id) VALUES (%(area_id)s, %(area_name)s, %(parent_area_id)s)"""
for row in data_statisticalareas:
    pgquery(conn, insert_stmt, row, "row inserted")

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(1) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(10) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(11) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(2) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(20) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(21) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(3) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(30) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(31) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(4) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(40) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(41) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(5) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(50) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(51) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(6) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(60) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(61) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(7) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(70) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(71) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(8) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(80) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(9) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(90) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(102) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(10201) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(102011028) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(102011029) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(102011030) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(102011031) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(102011032) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(102011033) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(102011034) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(102011035) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(102011036) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(102011037) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(102011038) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(102011039) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(102011040) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(102011041) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(102011042) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(102011043) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(10202) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(102021044) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(102021045) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(102021046) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(102021047) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(102021048) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(102021049) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(102021050) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(102021051) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(102021052) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(102021053) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(102021054) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(102021055) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(102021056) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(102021057) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(103) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(104) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(105) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(106) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(107) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(108) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(109) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(110) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(111) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(112) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(113) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(114) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(115) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(11501) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(115011290) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(115011291) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(115011294) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(115011296) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(115011553) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(115011554) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(115011555) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(115011556) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(115011557) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(115011558) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(115011559) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(11502) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(115021297) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(115021298) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(11503) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(115031299) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(115031300) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(11504) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(115041301) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(115041302) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(116) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(11601) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(116011303) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(116011304) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(116011306) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(116011307) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(116011308) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(116011560) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(116011561) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(11602) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(116021309) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(116021310) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(116021312) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(116021562) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(116021563) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(11603) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(116031313) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(116031314) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(116031315) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(116031316) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(116031317) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(116031318) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(116031319) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(117) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(11701) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(117011320) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(117011321) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(117011322) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(117011323) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(117011324) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(117011325) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(11702) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(117021326) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(117021327) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(117021328) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(11703) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(117031329) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(117031330) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(117031331) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(117031332) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(117031333) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(117031334) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(117031335) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(117031336) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(117031337) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(117031338) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(118) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(11801) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(118011339) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(118011340) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(118011341) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(118011342) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(118011343) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(118011344) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(118011345) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(118011346) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(118011347) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(11802) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(118021348) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(118021350) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(118021564) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(118021565) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(118021566) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(118021567) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(118021568) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(118021569) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(118021570) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(119) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(11901) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(119011354) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(119011355) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(119011356) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(119011357) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(119011358) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(119011359) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(119011360) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(119011361) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(119011571) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(119011572) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(11902) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(119021362) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(119021363) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(119021364) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(119021366) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(119021367) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(119021573) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(119021574) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(11903) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(119031368) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(119031369) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(119031370) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(119031371) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(119031372) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(119031373) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(119031374) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(11904) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(119041375) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(119041376) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(119041377) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(119041378) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(119041379) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(119041380) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(119041381) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(119041382) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(120) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(12001) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(120011383) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(120011384) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(120011385) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(120011386) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(12002) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(120021387) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(120021388) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(120021389) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(12003) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(120031390) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(120031391) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(120031392) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(120031393) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(120031394) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(120031395) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(120031396) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(120031575) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(120031576) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(121) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(12101) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(121011398) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(121011399) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(121011400) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(121011401) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(121011402) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(12102) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(121021403) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(121021404) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(121021406) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(121021577) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(121021578) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(121021579) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(12103) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(121031407) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(121031408) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(121031409) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(121031410) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(121031411) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(121031412) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(12104) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(121041413) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(121041414) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(121041415) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(121041416) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(121041417) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(122) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(12201) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(122011418) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(122011419) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(12202) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(122021420) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(122021421) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(122021422) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(122021423) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(12203) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(122031424) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(122031425) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(122031426) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(122031427) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(122031428) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(122031429) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(122031430) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(122031431) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(122031432) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(123) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(12301) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(123011433) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(123011434) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(123011435) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(12302) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(123021436) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(123021437) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(123021438) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(123021439) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(123021440) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(123021441) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(123021442) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(123021443) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(123021444) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(12303) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(123031445) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(123031446) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(123031447) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(123031448) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(124) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(12401) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(124011449) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(124011450) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(124011451) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(124011452) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(124011453) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(124011454) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(124011455) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(12402) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(124021456) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(12403) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(124031457) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(124031458) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(124031459) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(124031460) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(124031461) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(124031462) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(124031463) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(124031464) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(124031465) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(12404) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(124041466) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(124041467) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(124041468) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(12405) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(124051469) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(124051470) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(124051580) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(124051581) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(125) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(12501) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(125011473) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(125011475) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(125011582) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(125011583) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(125011584) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(125011585) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(125011586) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(125011587) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(12502) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(125021476) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(125021477) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(125021478) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(12503) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(125031479) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(125031480) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(125031481) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(125031482) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(125031483) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(125031484) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(125031485) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(125031486) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(125031487) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(12504) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(125041489) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(125041490) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(125041491) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(125041492) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(125041493) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(125041494) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(125041588) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(125041589) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(126) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(12601) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(126011495) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(126011496) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(12602) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(126021497) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(126021498) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(126021499) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(126021500) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(126021501) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(126021503) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(126021590) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(126021591) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(127) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(12701) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(127011504) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(127011505) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(127011506) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(127011592) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(127011593) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(127011594) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(127011595) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(127011596) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(127011597) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(12702) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(127021509) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(127021510) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(127021511) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(127021512) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(127021513) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(127021514) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(127021515) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(127021516) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(127021517) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(127021518) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(127021519) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(127021520) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(127021521) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(12703) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(127031522) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(127031523) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(127031524) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(127031598) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(127031599) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(127031600) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(127031601) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(128) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(12801) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(128011529) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(128011530) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(128011531) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(128011602) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(128011603) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(128011604) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(128011605) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(128011606) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(12802) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(128021533) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(128021534) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(128021535) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(128021536) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(128021537) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(128021538) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(128021607) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(128021608) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(128021609) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(197) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(19797) already exists.

db read error: row inserted
duplicate key value violates unique constraint "statisticalareas_pkey"
DETAIL:  Key (area_id)=(197979799) already exists.

In [37]:
businessstats_schema=''' CREATE TABLE IF NOT EXISTS businessstats(
                            area_id integer NOT NULL,
                            num_businesses integer,
                            retail_trade integer,
                            accommodation_and_food_services integer,
                            health_care_and_social_assistance integer,
                            education_and_training integer,
                            arts_and_recreation_services integer,
                            CONSTRAINT bussinessstats_pkey PRIMARY KEY (area_id),
                            CONSTRAINT bussinessstats_area_id_fkey FOREIGN KEY (area_id)
                            REFERENCES public.statisticalareas (area_id) MATCH SIMPLE)'''

pgquery(conn, "DROP TABLE businessstats",msg="cleared old table")
pgquery(conn, businessstats_schema, msg="created businessstats")

success: cleared old table
success: created businessstats

In [39]:
insert_stmt = """INSERT INTO businessstats(area_id,num_businesses,retail_trade,accommodation_and_food_services,health_care_and_social_assistance,
education_and_training,arts_and_recreation_services) VALUES (%(area_id)s, %(num_businesses)s, %(retail_trade)s,
%(accommodation_and_food_services)s,%(health_care_and_social_assistance)s, %(education_and_training)s, 
%(arts_and_recreation_services)s)"""
for row in data_businessstats:
    #use average value to handle null
    if row['num_businesses']=='':row['num_businesses']=business_mean['num_businesses']
    if row['retail_trade']=='':row['retail_trade']=business_mean['retail_trade']
    if row['accommodation_and_food_services']=='':row['accommodation_and_food_services']=business_mean['accommodation_and_food_services']
    if row['health_care_and_social_assistance']=='':row['health_care_and_social_assistance']=business_mean['health_care_and_social_assistance']
    if row['education_and_training'] == '': row['education_and_training']=business_mean['education_and_training']
    if row['arts_and_recreation_services']=='':row['arts_and_recreation_services']=business_mean['arts_and_recreation_services']
for row in data_businessstats:
    pgquery(conn, insert_stmt, row, "row inserted")

success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted

In [41]:
censusstats_schema=''' CREATE TABLE IF NOT EXISTS censusstats(
                                area_id integer NOT NULL,
                                median_annual_household_income integer,
                                avg_monthly_rent integer,
                                CONSTRAINT censusstats_pkey PRIMARY KEY (area_id),
                                CONSTRAINT censusstats_area_id_fkey FOREIGN KEY (area_id)
                                REFERENCES public.statisticalareas (area_id) MATCH SIMPLE)'''

pgquery(conn, "DROP TABLE censusstats",msg="cleared old table")
pgquery(conn, censusstats_schema, msg="created censusstats")

success: cleared old table
success: created censusstats

In [42]:
insert_stmt = """INSERT INTO censusstats(area_id,median_annual_household_income,avg_monthly_rent) VALUES (%(area_id)s, %(median_annual_household_income)s, %(avg_monthly_rent)s)"""
for row in data_censusstats:
    if row['median_annual_household_income']=='':row['median_annual_household_income']=censuss_mean['median_annual_household_income']
    if row['avg_monthly_rent']=='':row['avg_monthly_rent']=censuss_mean['avg_monthly_rent']
for row in data_censusstats:
    pgquery(conn, insert_stmt, row, "row inserted")

success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted

In [46]:
neighbourhoods_schema=''' CREATE TABLE IF NOT EXISTS neighbourhoods(
                                area_id integer NOT NULL,
                                area_name character varying(80),
                                land_area double precision,
                                population integer,
                                number_of_dwellings integer,
                                number_of_businesses integer,
                                CONSTRAINT neighbourhoods_pkey PRIMARY KEY (area_id),
                                CONSTRAINT neighbourhoods_area_id_fkey FOREIGN KEY (area_id)
                                REFERENCES public.statisticalareas (area_id) MATCH SIMPLE)'''

pgquery(conn, "DROP TABLE neighbourhoods",msg="cleared old table")
pgquery(conn, neighbourhoods_schema, msg="created neighbourhoods")

success: cleared old table
success: created neighbourhoods

In [47]:
insert_stmt = """INSERT INTO neighbourhoods(area_id,area_name,land_area,population,number_of_dwellings,number_of_businesses) 
                VALUES (%(area_id)s, %(area_name)s, %(land_area)s,%(population)s,%(number_of_dwellings)s,%(number_of_businesses)s)"""
for row in data_neighbourhoods:
    for i in row:
        if row[i]=='':row[i]=neighbourhoods_mean[i]
for row in data_neighbourhoods:
    pgquery(conn, insert_stmt, row, "row inserted")

success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted

In [9]:
bikesharingpods_schema='''CREATE TABLE public.bikesharingpods(
                          station_id integer NOT NULL,
                          name varchar(80) ,
                          num_bikes integer,
                          num_scooters integer,
                          geom GEOMETRY(Point,4326),
                          description text COLLATE pg_catalog."default",
                          CONSTRAINT bikesharingpods_pkey PRIMARY KEY (station_id))'''
pgquery(conn, "DROP TABLE bikesharingpods",msg="cleared old table")
pgquery(conn, bikesharingpods_schema, msg="created bikesharingpods")

success: cleared old table
success: created bikesharingpods

In [10]:
insert_stmt = """INSERT INTO bikesharingpods(station_id ,name,num_bikes,num_scooters,geom,description) 
                VALUES (%(station_id)s, %(name)s, %(num_bikes)s,%(num_scooters)s,ST_GEOMFROMTEXT(%(geom)s, 4326) ,%(description)s)"""
for row in data_bikesharingpods:
    row['geom']='Point('+row['longitude']+' '+row['latitude']+')'
for row in data_bikesharingpods:
    pgquery(conn, insert_stmt, row, "row inserted")

success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted

success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted

## 3.Calculate Cyclability-score as given

In [8]:
import numpy as np
podsquery='''select area_id,count(station_id),land_area,count(station_id)/land_area as bikepod_density
from neighbourhoods n left outer join 
(select *
from bikesharingpods b , aust au
where st_contains(au.geom,b.geom))
as pods
on (pods.sa2_main16=n.area_id)
group by area_id
order by area_id'''
podsresponse=pgquery( conn, podsquery)
podsmeasures=[]
for row in podsresponse:
    podsmeasures+=[row[3]]
podsmean=np.mean(podsmeasures)
podsstd=np.std(podsmeasures)
zbikepods=[]
for row in podsresponse:
    newdic={}
    newdic['area_id']=row[0]
    newdic['z_bikepods_density']=(row[3]-podsmean)/podsstd
    zbikepods+=[newdic]

In [6]:
zbikepods_schema=''' CREATE TABLE IF NOT EXISTS zbikepods(
                        area_id integer NOT NULL,
                        z_bikepods_density float,
                        CONSTRAINT zbikepods_pkey PRIMARY KEY (area_id),
                        CONSTRAINT zbikepods_area_id_fkey FOREIGN KEY (area_id)
                        REFERENCES public.statisticalareas (area_id) MATCH SIMPLE)'''
pgquery(conn, "DROP TABLE zbikepods",msg="cleared old table")
pgquery(conn, zbikepods_schema, msg="created zbikepods table")

db read error: cleared old table
table "zbikepods" does not exist

success: created zbikepods table

In [9]:
insert_stmt = """INSERT INTO zbikepods(area_id,z_bikepods_density) VALUES (%(area_id)s, %(z_bikepods_density)s)"""
for row in zbikepods:
    pgquery(conn, insert_stmt, row, "row inserted")

success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted

In [10]:
populationquery='''select area_id,(population/land_area-avg)/sd as z_population_density from neighbourhoods N 
,(select avg(population/land_area) as "avg",stddev(population/land_area) as sd from neighbourhoods) as st
'''
populationresponse=pgquery( conn, populationquery)
zpopulation=[]
for row in populationresponse:
    newdic={}
    newdic['area_id']=row[0]
    newdic['z_population_density']=row[1]
    zpopulation+=[newdic]

In [11]:
zpopulation_schema=''' CREATE TABLE IF NOT EXISTS zpopulation(
                        area_id integer NOT NULL,
                        z_population_density float,
                        CONSTRAINT zpopulation_pkey PRIMARY KEY (area_id),
                        CONSTRAINT zpopulation_area_id_fkey FOREIGN KEY (area_id)
                        REFERENCES public.statisticalareas (area_id) MATCH SIMPLE)'''
pgquery(conn, "DROP TABLE zpopulation",msg="cleared old table")
pgquery(conn, zpopulation_schema, msg="created zpopulation table")

success: cleared old table
success: created zpopulation table

In [12]:
insert_stmt = """INSERT INTO zpopulation(area_id,z_population_density) VALUES (%(area_id)s, %(z_population_density)s)"""
for row in zpopulation:
    pgquery(conn, insert_stmt, row, "row inserted")

success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted

In [13]:
dwellingquery='''select area_id,(number_of_dwellings/land_area-avg)/sd as z_number_of_dwellings_density 
from neighbourhoods N ,
(select avg(number_of_dwellings/land_area) as "avg",stddev(number_of_dwellings/land_area) as sd 
 from neighbourhoods) as st'''
dwellingresponse=pgquery( conn, dwellingquery)
zdwelling=[]
for row in dwellingresponse:
    newdic={}
    newdic['area_id']=row[0]
    newdic['z_dwelling_density']=row[1]
    zdwelling+=[newdic]

In [14]:
zdwelling_schema=''' CREATE TABLE IF NOT EXISTS zdwelling(
                        area_id integer NOT NULL,
                        z_dwelling_density float,
                        CONSTRAINT zdwelling_pkey PRIMARY KEY (area_id),
                        CONSTRAINT zdwelling_area_id_fkey FOREIGN KEY (area_id)
                        REFERENCES public.statisticalareas (area_id) MATCH SIMPLE)'''
pgquery(conn, "DROP TABLE zdwelling",msg="cleared old table")
pgquery(conn, zdwelling_schema, msg="created zdwelling table")

success: cleared old table
success: created zdwelling table

In [15]:
insert_stmt = """INSERT INTO zdwelling(area_id,z_dwelling_density) VALUES (%(area_id)s, %(z_dwelling_density)s)"""
for row in zdwelling:
    pgquery(conn, insert_stmt, row, "row inserted")

success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted

In [16]:
servicequery='''select area_id,(measure-avg)/stddev
from(
select avg(measure),stddev(measure)
from
(select area_id,num_businesses*a/sum+retail_trade*b/sum+accommodation_and_food_services*c/sum+health_care_and_social_assistance*d/sum+
education_and_training*e/sum+arts_and_recreation_services*f/sum as measure
from businessstats,
(select avg(num_businesses) as a,avg(retail_trade) as b,avg(accommodation_and_food_services
) as c,avg(health_care_and_social_assistance
) as d,avg(education_and_training
) as e,avg(arts_and_recreation_services
) as f,avg(num_businesses)+avg(retail_trade)+avg(accommodation_and_food_services
)+avg(health_care_and_social_assistance
)+avg(education_and_training
)+avg(arts_and_recreation_services
) as sum  from businessstats) as st)
as mea
) as std,
(select area_id,num_businesses*a/sum+retail_trade*b/sum+accommodation_and_food_services*c/sum+health_care_and_social_assistance*d/sum+
education_and_training*e/sum+arts_and_recreation_services*f/sum as measure
from businessstats,
(select avg(num_businesses) as a,avg(retail_trade) as b,avg(accommodation_and_food_services
) as c,avg(health_care_and_social_assistance
) as d,avg(education_and_training
) as e,avg(arts_and_recreation_services
) as f,avg(num_businesses)+avg(retail_trade)+avg(accommodation_and_food_services
)+avg(health_care_and_social_assistance
)+avg(education_and_training
)+avg(arts_and_recreation_services
) as sum  from businessstats) as st)
as mea'''
serviceresponse=pgquery( conn, servicequery)
zservice=[]
for row in serviceresponse:
    newdic={}
    newdic['area_id']=row[0]
    newdic['z_service_balance']=row[1]
    zservice+=[newdic]

In [17]:
zservice_schema=''' CREATE TABLE IF NOT EXISTS zservice(
                        area_id integer NOT NULL,
                        z_service_balance float,
                        CONSTRAINT zservice_pkey PRIMARY KEY (area_id),
                        CONSTRAINT zservice_area_id_fkey FOREIGN KEY (area_id)
                        REFERENCES public.statisticalareas (area_id) MATCH SIMPLE)'''
pgquery(conn, "DROP TABLE zservice",msg="cleared old table")
pgquery(conn, zservice_schema, msg="created zservice table")

success: cleared old table
success: created zservice table

In [18]:
insert_stmt = """INSERT INTO zservice(area_id,z_service_balance) VALUES (%(area_id)s, %(z_service_balance)s)"""
for row in zservice:
    pgquery(conn, insert_stmt, row, "row inserted")

success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted